<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <LangVersion>latestmajor</LangVersion>
    <Version>0.6.1</Version>
    <Authors>Olivier Azeau</Authors>
    <Product>AvaloniaGraphControl</Product>
    <PackageId>AvaloniaGraphControl</PackageId>
    <NeutralLanguage>en</NeutralLanguage>
    <Description>A graph layout panel for AvaloniaUI</Description>
    <Copyright>Copyright © Olivier Azeau</Copyright>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <RepositoryUrl>https://github.com/Oaz/AvaloniaGraphControl.git</RepositoryUrl>
    <PackageProjectUrl>https://github.com/Oaz/AvaloniaGraphControl</PackageProjectUrl>
    <PackageTags>Avalonia Graph Control MSAGL</PackageTags>
    <PackageRequireLicenseAcceptance>true</PackageRequireLicenseAcceptance>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageReleaseNotes>Release</PackageReleaseNotes>
    <TargetsForTfmSpecificBuildOutput>$(TargetsForTfmSpecificBuildOutput);IncludePrivateDependenciesInNupkg</TargetsForTfmSpecificBuildOutput>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutomaticGraphLayout" Version="1.1.12" />
    <PackageReference Include="AutomaticGraphLayout.Drawing" Version="1.1.12" />
    <PackageReference Include="Avalonia" Version="$(AvaloniaVersion)" />
    <None Include="..\README.md" Pack="true" PackagePath="\"/>
  </ItemGroup>
  <Target Name="IncludePrivateDependenciesInNupkg">
    <ItemGroup>
      <BuildOutputInPackage Include="$(OutputPath)AutomaticGraphLayout.dll" />
      <BuildOutputInPackage Include="$(OutputPath)AutomaticGraphLayout.Drawing.dll" />
    </ItemGroup>
  </Target>
</Project>
